version: "1"

services:
  blog:
    image: ghost:latest
    ports:
      - "60000:2368"
    volumes:
      - /Users/yeomjaeseon/study/docker/assignments/ghost:/var/lib/ghost/content
    environment:
      url: http://localhost:60000